name: cosecheros
description: Cosecheros de Granizo en Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
version: 8.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # utils
  google_fonts: ^2.2.0
  url_launcher: ^6.0.17
  provider: ^5.0.0
  image_picker: ^0.8.4+4
  package_info_plus: ^1.3.0
  stream_transform: ^2.0.0
  flutter_svg: ^1.0.0
  flutter_linkify: ^5.0.2

  # caches
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0

  # formatters
  intl: ^0.17.0
  timeago: ^3.1.0

  # maps and gps
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2+1
  geolocator: ^8.0.1
  geocoding: ^2.0.1

  # firebase
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.4
  firebase_storage: ^10.2.15
  firebase_analytics: ^9.1.2
  firebase_remote_config: ^1.0.3
  firebase_crashlytics: ^2.4.4
  firebase_messaging: ^11.2.12

  # login
  google_sign_in: ^5.2.1

  # forms
  flutter_dynamic_forms: ^1.0.0
  flutter_dynamic_forms_components: ^1.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#5C92FF"
  adaptive_icon_foreground: "assets/icon-fore.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon-fore.png
    - assets/app/
    - firebase/hosting/forms/
